### ISSUE TITLE
should run ./autogen.sh in monolinguals

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-init#21]
That way, you can do 

```
apertium-init foo
apertium-init bar
apertium-init foo-bar
cd apertium-foo-bar
./autogen.sh --with-lang1=../apertium-foo --with-lang2=../apertium-bar
make langs
```

**Comment by unhammer** [comment]
I was thinking

4. apertium-init should execute autogen.sh in a new monolingual module.

since that kind of thing sounds horribly complicated to encode in makefiles

**Comment by jonorthwash** [comment]
Ah, in that case I believe this issue was interpreted correctly by @mr-martian.

I'm not sure how "safe" this is.  Also, it means people starting entirely from scratch won't know about autogen in the language modules, but people cloning an existing module will still need to know.  I guess there's always a trade-off between making things happen magically and teaching people about them.

**Comment by mr-martian** [comment]
My inclination would be to tell everyone to use `apertium-get` (which also runs autogen)
